package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int idActividad;
     private Inscripcion inscripcion;
     private Unidad unidad;
     private String nombre;
     private String tipo;
     private BigDecimal calificacion;
     private Boolean borradoLogico;

    public Actividad() {
    }

	
    public Actividad(int idActividad, String nombre, String tipo) {
        this.idActividad = idActividad;
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Actividad(int idActividad, Inscripcion inscripcion, Unidad unidad, String nombre, String tipo, BigDecimal calificacion, Boolean borradoLogico) {
       this.idActividad = idActividad;
       this.inscripcion = inscripcion;
       this.unidad = unidad;
       this.nombre = nombre;
       this.tipo = tipo;
       this.calificacion = calificacion;
       this.borradoLogico = borradoLogico;
    }
   
    public int getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }
    public Inscripcion getInscripcion() {
        return this.inscripcion;
    }
    
    public void setInscripcion(Inscripcion inscripcion) {
        this.inscripcion = inscripcion;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(BigDecimal calificacion) {
        this.calificacion = calificacion;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }




}


