package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private Integer idAdministrador;
     private long cui;
     private String nombre;
     private String apellido;
     private String telefono;
     private String contrasenia;
     private Boolean borradoLogico;
     private Set<Escuela> escuelas = new HashSet<Escuela>(0);

    public Administrador() {
    }

	
    public Administrador(long cui, String nombre, String apellido, String telefono, String contrasenia) {
        this.cui = cui;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.contrasenia = contrasenia;
    }
    public Administrador(long cui, String nombre, String apellido, String telefono, String contrasenia, Boolean borradoLogico, Set<Escuela> escuelas) {
       this.cui = cui;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.contrasenia = contrasenia;
       this.borradoLogico = borradoLogico;
       this.escuelas = escuelas;
    }
   
    public Integer getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(Integer idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public long getCui() {
        return this.cui;
    }
    
    public void setCui(long cui) {
        this.cui = cui;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Escuela> getEscuelas() {
        return this.escuelas;
    }
    
    public void setEscuelas(Set<Escuela> escuelas) {
        this.escuelas = escuelas;
    }




}


