package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Anioescolar generated by hbm2java
 */
public class Anioescolar  implements java.io.Serializable {


     private int idAnio;
     private String nombreAnio;
     private Boolean borradoLogico;
     private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

    public Anioescolar() {
    }

	
    public Anioescolar(int idAnio, String nombreAnio) {
        this.idAnio = idAnio;
        this.nombreAnio = nombreAnio;
    }
    public Anioescolar(int idAnio, String nombreAnio, Boolean borradoLogico, Set<Inscripcion> inscripcions) {
       this.idAnio = idAnio;
       this.nombreAnio = nombreAnio;
       this.borradoLogico = borradoLogico;
       this.inscripcions = inscripcions;
    }
   
    public int getIdAnio() {
        return this.idAnio;
    }
    
    public void setIdAnio(int idAnio) {
        this.idAnio = idAnio;
    }
    public String getNombreAnio() {
        return this.nombreAnio;
    }
    
    public void setNombreAnio(String nombreAnio) {
        this.nombreAnio = nombreAnio;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Inscripcion> getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set<Inscripcion> inscripcions) {
        this.inscripcions = inscripcions;
    }




}


