package POJOs;
// Generated 29-sep-2024 19:19:33 by Hibernate Tools 4.3.1



/**
 * AsignacionDocenteCurso generated by hbm2java
 */
public class AsignacionDocenteCurso  implements java.io.Serializable {


     private Integer idAsignacion;
     private Curso curso;
     private Docente docente;
     private Seccion seccion;
     private Boolean borradoLogico;

    public AsignacionDocenteCurso() {
    }

    public AsignacionDocenteCurso(Curso curso, Docente docente, Seccion seccion, Boolean borradoLogico) {
       this.curso = curso;
       this.docente = docente;
       this.seccion = seccion;
       this.borradoLogico = borradoLogico;
    }
   
    public Integer getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(Integer idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }




}


