package POJOs;
// Generated 23/09/2024 12:41:05 PM by Hibernate Tools 4.3.1



/**
 * AsignacionDocenteEscuela generated by hbm2java
 */
public class AsignacionDocenteEscuela  implements java.io.Serializable {


     private int idAsignacion;
     private Docente docente;
     private Escuela escuela;

    public AsignacionDocenteEscuela() {
    }

	
    public AsignacionDocenteEscuela(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public AsignacionDocenteEscuela(int idAsignacion, Docente docente, Escuela escuela) {
       this.idAsignacion = idAsignacion;
       this.docente = docente;
       this.escuela = escuela;
    }
   
    public int getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }




}


