package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private int idCalificacion;
     private Inscripcion inscripcion;
     private Unidad unidad;
     private BigDecimal zonaTotal;
     private BigDecimal evaluacionFinal;
     private BigDecimal totalFinal;
     private Boolean promovido;

    public Calificacion() {
    }

	
    public Calificacion(int idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Calificacion(int idCalificacion, Inscripcion inscripcion, Unidad unidad, BigDecimal zonaTotal, BigDecimal evaluacionFinal, BigDecimal totalFinal, Boolean promovido) {
       this.idCalificacion = idCalificacion;
       this.inscripcion = inscripcion;
       this.unidad = unidad;
       this.zonaTotal = zonaTotal;
       this.evaluacionFinal = evaluacionFinal;
       this.totalFinal = totalFinal;
       this.promovido = promovido;
    }
   
    public int getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(int idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Inscripcion getInscripcion() {
        return this.inscripcion;
    }
    
    public void setInscripcion(Inscripcion inscripcion) {
        this.inscripcion = inscripcion;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public BigDecimal getZonaTotal() {
        return this.zonaTotal;
    }
    
    public void setZonaTotal(BigDecimal zonaTotal) {
        this.zonaTotal = zonaTotal;
    }
    public BigDecimal getEvaluacionFinal() {
        return this.evaluacionFinal;
    }
    
    public void setEvaluacionFinal(BigDecimal evaluacionFinal) {
        this.evaluacionFinal = evaluacionFinal;
    }
    public BigDecimal getTotalFinal() {
        return this.totalFinal;
    }
    
    public void setTotalFinal(BigDecimal totalFinal) {
        this.totalFinal = totalFinal;
    }
    public Boolean getPromovido() {
        return this.promovido;
    }
    
    public void setPromovido(Boolean promovido) {
        this.promovido = promovido;
    }




}


