package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CicloEscolar generated by hbm2java
 */
public class CicloEscolar  implements java.io.Serializable {


     private int idCiclo;
     private Escuela escuela;
     private int anio;
     private String estado;
     private Boolean borradoLogico;
     private Set<Grado> grados = new HashSet<Grado>(0);

    public CicloEscolar() {
    }

	
    public CicloEscolar(int idCiclo, int anio) {
        this.idCiclo = idCiclo;
        this.anio = anio;
    }
    public CicloEscolar(int idCiclo, Escuela escuela, int anio, String estado, Boolean borradoLogico, Set<Grado> grados) {
       this.idCiclo = idCiclo;
       this.escuela = escuela;
       this.anio = anio;
       this.estado = estado;
       this.borradoLogico = borradoLogico;
       this.grados = grados;
    }
   
    public int getIdCiclo() {
        return this.idCiclo;
    }
    
    public void setIdCiclo(int idCiclo) {
        this.idCiclo = idCiclo;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Grado> getGrados() {
        return this.grados;
    }
    
    public void setGrados(Set<Grado> grados) {
        this.grados = grados;
    }




}


