package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private Escuela escuela;
     private Grado grado;
     private String nombre;
     private Boolean borradoLogico;
     private Set<Unidad> unidads = new HashSet<Unidad>(0);
     private Set<Cursodocente> cursodocentes = new HashSet<Cursodocente>(0);

    public Curso() {
    }

	
    public Curso(int idCurso, String nombre) {
        this.idCurso = idCurso;
        this.nombre = nombre;
    }
    public Curso(int idCurso, Escuela escuela, Grado grado, String nombre, Boolean borradoLogico, Set<Unidad> unidads, Set<Cursodocente> cursodocentes) {
       this.idCurso = idCurso;
       this.escuela = escuela;
       this.grado = grado;
       this.nombre = nombre;
       this.borradoLogico = borradoLogico;
       this.unidads = unidads;
       this.cursodocentes = cursodocentes;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Unidad> getUnidads() {
        return this.unidads;
    }
    
    public void setUnidads(Set<Unidad> unidads) {
        this.unidads = unidads;
    }
    public Set<Cursodocente> getCursodocentes() {
        return this.cursodocentes;
    }
    
    public void setCursodocentes(Set<Cursodocente> cursodocentes) {
        this.cursodocentes = cursodocentes;
    }




}


