package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private Grado grado;
     private String nombreCurso;
     private Boolean borradoLogico;
     private Set<Actividad> actividads = new HashSet<Actividad>(0);
     private Set<AsignacionDocenteCurso> asignacionDocenteCursos = new HashSet<AsignacionDocenteCurso>(0);

    public Curso() {
    }

	
    public Curso(int idCurso, String nombreCurso) {
        this.idCurso = idCurso;
        this.nombreCurso = nombreCurso;
    }
    public Curso(int idCurso, Grado grado, String nombreCurso, Boolean borradoLogico, Set<Actividad> actividads, Set<AsignacionDocenteCurso> asignacionDocenteCursos) {
       this.idCurso = idCurso;
       this.grado = grado;
       this.nombreCurso = nombreCurso;
       this.borradoLogico = borradoLogico;
       this.actividads = actividads;
       this.asignacionDocenteCursos = asignacionDocenteCursos;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Actividad> getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set<Actividad> actividads) {
        this.actividads = actividads;
    }
    public Set<AsignacionDocenteCurso> getAsignacionDocenteCursos() {
        return this.asignacionDocenteCursos;
    }
    
    public void setAsignacionDocenteCursos(Set<AsignacionDocenteCurso> asignacionDocenteCursos) {
        this.asignacionDocenteCursos = asignacionDocenteCursos;
    }




}


