package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1



/**
 * Director generated by hbm2java
 */
public class Director  implements java.io.Serializable {


     private int idDirector;
     private Escuela escuela;
     private String nombre;
     private String apellido;
     private String telefono;
     private String contrasenia;
     private Boolean borradoLogico;

    public Director() {
    }

	
    public Director(int idDirector, String nombre, String apellido, String telefono, String contrasenia) {
        this.idDirector = idDirector;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.contrasenia = contrasenia;
    }
    public Director(int idDirector, Escuela escuela, String nombre, String apellido, String telefono, String contrasenia, Boolean borradoLogico) {
       this.idDirector = idDirector;
       this.escuela = escuela;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.contrasenia = contrasenia;
       this.borradoLogico = borradoLogico;
    }
   
    public int getIdDirector() {
        return this.idDirector;
    }
    
    public void setIdDirector(int idDirector) {
        this.idDirector = idDirector;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }




}


