package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer idDocente;
     private String codigoPersonal;
     private long cui;
     private String contrasenia;
     private Boolean borradoLogico;
     private Set<AsignacionDocenteCurso> asignacionDocenteCursos = new HashSet<AsignacionDocenteCurso>(0);

    public Docente() {
    }

	
    public Docente(String codigoPersonal, long cui, String contrasenia) {
        this.codigoPersonal = codigoPersonal;
        this.cui = cui;
        this.contrasenia = contrasenia;
    }
    public Docente(String codigoPersonal, long cui, String contrasenia, Boolean borradoLogico, Set<AsignacionDocenteCurso> asignacionDocenteCursos) {
       this.codigoPersonal = codigoPersonal;
       this.cui = cui;
       this.contrasenia = contrasenia;
       this.borradoLogico = borradoLogico;
       this.asignacionDocenteCursos = asignacionDocenteCursos;
    }
   
    public Integer getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(Integer idDocente) {
        this.idDocente = idDocente;
    }
    public String getCodigoPersonal() {
        return this.codigoPersonal;
    }
    
    public void setCodigoPersonal(String codigoPersonal) {
        this.codigoPersonal = codigoPersonal;
    }
    public long getCui() {
        return this.cui;
    }
    
    public void setCui(long cui) {
        this.cui = cui;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<AsignacionDocenteCurso> getAsignacionDocenteCursos() {
        return this.asignacionDocenteCursos;
    }
    
    public void setAsignacionDocenteCursos(Set<AsignacionDocenteCurso> asignacionDocenteCursos) {
        this.asignacionDocenteCursos = asignacionDocenteCursos;
    }




}


