package POJOs;
// Generated 29-sep-2024 19:19:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer idDocente;
     private Escuela escuela;
     private String codigoPersonal;
     private long cui;
     private String contrasenia;
     private Boolean borradoLogico;
     private Set asignacionDocenteCursos = new HashSet(0);
     private Set asignacionDocenteEscuelas = new HashSet(0);

    public Docente() {
    }

	
    public Docente(String codigoPersonal, long cui, String contrasenia) {
        this.codigoPersonal = codigoPersonal;
        this.cui = cui;
        this.contrasenia = contrasenia;
    }
    public Docente(Escuela escuela, String codigoPersonal, long cui, String contrasenia, Boolean borradoLogico, Set asignacionDocenteCursos, Set asignacionDocenteEscuelas) {
       this.escuela = escuela;
       this.codigoPersonal = codigoPersonal;
       this.cui = cui;
       this.contrasenia = contrasenia;
       this.borradoLogico = borradoLogico;
       this.asignacionDocenteCursos = asignacionDocenteCursos;
       this.asignacionDocenteEscuelas = asignacionDocenteEscuelas;
    }
   
    public Integer getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(Integer idDocente) {
        this.idDocente = idDocente;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getCodigoPersonal() {
        return this.codigoPersonal;
    }
    
    public void setCodigoPersonal(String codigoPersonal) {
        this.codigoPersonal = codigoPersonal;
    }
    public long getCui() {
        return this.cui;
    }
    
    public void setCui(long cui) {
        this.cui = cui;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set getAsignacionDocenteCursos() {
        return this.asignacionDocenteCursos;
    }
    
    public void setAsignacionDocenteCursos(Set asignacionDocenteCursos) {
        this.asignacionDocenteCursos = asignacionDocenteCursos;
    }
    public Set getAsignacionDocenteEscuelas() {
        return this.asignacionDocenteEscuelas;
    }
    
    public void setAsignacionDocenteEscuelas(Set asignacionDocenteEscuelas) {
        this.asignacionDocenteEscuelas = asignacionDocenteEscuelas;
    }




}


