package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private String codigoEscuela;
     private Administrador administrador;
     private String nombre;
     private String direccion;
     private Boolean borradoLogico;
     private Set<CicloEscolar> cicloEscolars = new HashSet<CicloEscolar>(0);
     private Set<Director> directors = new HashSet<Director>(0);

    public Escuela() {
    }

	
    public Escuela(String codigoEscuela, String nombre) {
        this.codigoEscuela = codigoEscuela;
        this.nombre = nombre;
    }
    public Escuela(String codigoEscuela, Administrador administrador, String nombre, String direccion, Boolean borradoLogico, Set<CicloEscolar> cicloEscolars, Set<Director> directors) {
       this.codigoEscuela = codigoEscuela;
       this.administrador = administrador;
       this.nombre = nombre;
       this.direccion = direccion;
       this.borradoLogico = borradoLogico;
       this.cicloEscolars = cicloEscolars;
       this.directors = directors;
    }
   
    public String getCodigoEscuela() {
        return this.codigoEscuela;
    }
    
    public void setCodigoEscuela(String codigoEscuela) {
        this.codigoEscuela = codigoEscuela;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<CicloEscolar> getCicloEscolars() {
        return this.cicloEscolars;
    }
    
    public void setCicloEscolars(Set<CicloEscolar> cicloEscolars) {
        this.cicloEscolars = cicloEscolars;
    }
    public Set<Director> getDirectors() {
        return this.directors;
    }
    
    public void setDirectors(Set<Director> directors) {
        this.directors = directors;
    }




}


