package POJOs;
// Generated 29-sep-2024 19:19:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private String codigoEscuela;
     private Administrador administrador;
     private String nombre;
     private String direccion;
     private Boolean borradoLogico;
     private Set grados = new HashSet(0);
     private Set cicloEscolars = new HashSet(0);
     private Set docentes = new HashSet(0);
     private Set directors = new HashSet(0);
     private Set asignacionDocenteEscuelas = new HashSet(0);

    public Escuela() {
    }

	
    public Escuela(String codigoEscuela, String nombre) {
        this.codigoEscuela = codigoEscuela;
        this.nombre = nombre;
    }
    public Escuela(String codigoEscuela, Administrador administrador, String nombre, String direccion, Boolean borradoLogico, Set grados, Set cicloEscolars, Set docentes, Set directors, Set asignacionDocenteEscuelas) {
       this.codigoEscuela = codigoEscuela;
       this.administrador = administrador;
       this.nombre = nombre;
       this.direccion = direccion;
       this.borradoLogico = borradoLogico;
       this.grados = grados;
       this.cicloEscolars = cicloEscolars;
       this.docentes = docentes;
       this.directors = directors;
       this.asignacionDocenteEscuelas = asignacionDocenteEscuelas;
    }
   
    public String getCodigoEscuela() {
        return this.codigoEscuela;
    }
    
    public void setCodigoEscuela(String codigoEscuela) {
        this.codigoEscuela = codigoEscuela;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set getGrados() {
        return this.grados;
    }
    
    public void setGrados(Set grados) {
        this.grados = grados;
    }
    public Set getCicloEscolars() {
        return this.cicloEscolars;
    }
    
    public void setCicloEscolars(Set cicloEscolars) {
        this.cicloEscolars = cicloEscolars;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getDirectors() {
        return this.directors;
    }
    
    public void setDirectors(Set directors) {
        this.directors = directors;
    }
    public Set getAsignacionDocenteEscuelas() {
        return this.asignacionDocenteEscuelas;
    }
    
    public void setAsignacionDocenteEscuelas(Set asignacionDocenteEscuelas) {
        this.asignacionDocenteEscuelas = asignacionDocenteEscuelas;
    }




}


