package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private String codigoEscuela;
     private String nombre;
     private String direccion;
     private String telefono;
     private Boolean borradoLogico;
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Grado> grados = new HashSet<Grado>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<Seccion> seccions = new HashSet<Seccion>(0);

    public Escuela() {
    }

	
    public Escuela(String codigoEscuela, String nombre, String direccion, String telefono) {
        this.codigoEscuela = codigoEscuela;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Escuela(String codigoEscuela, String nombre, String direccion, String telefono, Boolean borradoLogico, Set<Persona> personas, Set<Grado> grados, Set<Usuario> usuarios, Set<Curso> cursos, Set<Seccion> seccions) {
       this.codigoEscuela = codigoEscuela;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.borradoLogico = borradoLogico;
       this.personas = personas;
       this.grados = grados;
       this.usuarios = usuarios;
       this.cursos = cursos;
       this.seccions = seccions;
    }
   
    public String getCodigoEscuela() {
        return this.codigoEscuela;
    }
    
    public void setCodigoEscuela(String codigoEscuela) {
        this.codigoEscuela = codigoEscuela;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<Grado> getGrados() {
        return this.grados;
    }
    
    public void setGrados(Set<Grado> grados) {
        this.grados = grados;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
    public Set<Seccion> getSeccions() {
        return this.seccions;
    }
    
    public void setSeccions(Set<Seccion> seccions) {
        this.seccions = seccions;
    }




}


