package POJOs;
// Generated 29-sep-2024 19:19:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private Integer idGrado;
     private CicloEscolar cicloEscolar;
     private Escuela escuela;
     private String nombreGrado;
     private Boolean borradoLogico;
     private Set cursos = new HashSet(0);
     private Set seccions = new HashSet(0);
     private Set historialGraduacions = new HashSet(0);

    public Grado() {
    }

	
    public Grado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Grado(CicloEscolar cicloEscolar, Escuela escuela, String nombreGrado, Boolean borradoLogico, Set cursos, Set seccions, Set historialGraduacions) {
       this.cicloEscolar = cicloEscolar;
       this.escuela = escuela;
       this.nombreGrado = nombreGrado;
       this.borradoLogico = borradoLogico;
       this.cursos = cursos;
       this.seccions = seccions;
       this.historialGraduacions = historialGraduacions;
    }
   
    public Integer getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(Integer idGrado) {
        this.idGrado = idGrado;
    }
    public CicloEscolar getCicloEscolar() {
        return this.cicloEscolar;
    }
    
    public void setCicloEscolar(CicloEscolar cicloEscolar) {
        this.cicloEscolar = cicloEscolar;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getNombreGrado() {
        return this.nombreGrado;
    }
    
    public void setNombreGrado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }
    public Set getSeccions() {
        return this.seccions;
    }
    
    public void setSeccions(Set seccions) {
        this.seccions = seccions;
    }
    public Set getHistorialGraduacions() {
        return this.historialGraduacions;
    }
    
    public void setHistorialGraduacions(Set historialGraduacions) {
        this.historialGraduacions = historialGraduacions;
    }




}


