package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private int idGrado;
     private Escuela escuela;
     private String nombre;
     private String nivel;
     private Boolean borradoLogico;
     private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<Seccion> seccions = new HashSet<Seccion>(0);

    public Grado() {
    }

	
    public Grado(int idGrado, String nombre, String nivel) {
        this.idGrado = idGrado;
        this.nombre = nombre;
        this.nivel = nivel;
    }
    public Grado(int idGrado, Escuela escuela, String nombre, String nivel, Boolean borradoLogico, Set<Inscripcion> inscripcions, Set<Usuario> usuarios, Set<Curso> cursos, Set<Seccion> seccions) {
       this.idGrado = idGrado;
       this.escuela = escuela;
       this.nombre = nombre;
       this.nivel = nivel;
       this.borradoLogico = borradoLogico;
       this.inscripcions = inscripcions;
       this.usuarios = usuarios;
       this.cursos = cursos;
       this.seccions = seccions;
    }
   
    public int getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(int idGrado) {
        this.idGrado = idGrado;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Inscripcion> getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set<Inscripcion> inscripcions) {
        this.inscripcions = inscripcions;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
    public Set<Seccion> getSeccions() {
        return this.seccions;
    }
    
    public void setSeccions(Set<Seccion> seccions) {
        this.seccions = seccions;
    }




}


