package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private int idGrado;
     private CicloEscolar cicloEscolar;
     private String nombreGrado;
     private Boolean borradoLogico;
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<Seccion> seccions = new HashSet<Seccion>(0);
     private Set<HistorialGraduacion> historialGraduacions = new HashSet<HistorialGraduacion>(0);

    public Grado() {
    }

	
    public Grado(int idGrado, String nombreGrado) {
        this.idGrado = idGrado;
        this.nombreGrado = nombreGrado;
    }
    public Grado(int idGrado, CicloEscolar cicloEscolar, String nombreGrado, Boolean borradoLogico, Set<Curso> cursos, Set<Seccion> seccions, Set<HistorialGraduacion> historialGraduacions) {
       this.idGrado = idGrado;
       this.cicloEscolar = cicloEscolar;
       this.nombreGrado = nombreGrado;
       this.borradoLogico = borradoLogico;
       this.cursos = cursos;
       this.seccions = seccions;
       this.historialGraduacions = historialGraduacions;
    }
   
    public int getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(int idGrado) {
        this.idGrado = idGrado;
    }
    public CicloEscolar getCicloEscolar() {
        return this.cicloEscolar;
    }
    
    public void setCicloEscolar(CicloEscolar cicloEscolar) {
        this.cicloEscolar = cicloEscolar;
    }
    public String getNombreGrado() {
        return this.nombreGrado;
    }
    
    public void setNombreGrado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
    public Set<Seccion> getSeccions() {
        return this.seccions;
    }
    
    public void setSeccions(Set<Seccion> seccions) {
        this.seccions = seccions;
    }
    public Set<HistorialGraduacion> getHistorialGraduacions() {
        return this.historialGraduacions;
    }
    
    public void setHistorialGraduacions(Set<HistorialGraduacion> historialGraduacions) {
        this.historialGraduacions = historialGraduacions;
    }




}


