package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1



/**
 * HistorialGraduacion generated by hbm2java
 */
public class HistorialGraduacion  implements java.io.Serializable {


     private int idHistorial;
     private Estudiante estudiante;
     private Grado grado;
     private Integer anio;
     private Boolean promovido;
     private Boolean borradoLogico;

    public HistorialGraduacion() {
    }

	
    public HistorialGraduacion(int idHistorial) {
        this.idHistorial = idHistorial;
    }
    public HistorialGraduacion(int idHistorial, Estudiante estudiante, Grado grado, Integer anio, Boolean promovido, Boolean borradoLogico) {
       this.idHistorial = idHistorial;
       this.estudiante = estudiante;
       this.grado = grado;
       this.anio = anio;
       this.promovido = promovido;
       this.borradoLogico = borradoLogico;
    }
   
    public int getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(int idHistorial) {
        this.idHistorial = idHistorial;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public Boolean getPromovido() {
        return this.promovido;
    }
    
    public void setPromovido(Boolean promovido) {
        this.promovido = promovido;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }




}


