package POJOs;
// Generated 29-sep-2024 19:19:33 by Hibernate Tools 4.3.1



/**
 * HistorialGraduacion generated by hbm2java
 */
public class HistorialGraduacion  implements java.io.Serializable {


     private Integer idHistorial;
     private CicloEscolar cicloEscolar;
     private Estudiante estudiante;
     private Grado grado;
     private Integer anio;
     private Boolean promovido;
     private Boolean borradoLogico;

    public HistorialGraduacion() {
    }

    public HistorialGraduacion(CicloEscolar cicloEscolar, Estudiante estudiante, Grado grado, Integer anio, Boolean promovido, Boolean borradoLogico) {
       this.cicloEscolar = cicloEscolar;
       this.estudiante = estudiante;
       this.grado = grado;
       this.anio = anio;
       this.promovido = promovido;
       this.borradoLogico = borradoLogico;
    }
   
    public Integer getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(Integer idHistorial) {
        this.idHistorial = idHistorial;
    }
    public CicloEscolar getCicloEscolar() {
        return this.cicloEscolar;
    }
    
    public void setCicloEscolar(CicloEscolar cicloEscolar) {
        this.cicloEscolar = cicloEscolar;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public Boolean getPromovido() {
        return this.promovido;
    }
    
    public void setPromovido(Boolean promovido) {
        this.promovido = promovido;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }




}


