package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private int idInscripcion;
     private Anioescolar anioescolar;
     private Estudiante estudiante;
     private Grado grado;
     private Seccion seccion;
     private Set<Actividad> actividads = new HashSet<Actividad>(0);
     private Set<Calificacion> calificacions = new HashSet<Calificacion>(0);

    public Inscripcion() {
    }

	
    public Inscripcion(int idInscripcion) {
        this.idInscripcion = idInscripcion;
    }
    public Inscripcion(int idInscripcion, Anioescolar anioescolar, Estudiante estudiante, Grado grado, Seccion seccion, Set<Actividad> actividads, Set<Calificacion> calificacions) {
       this.idInscripcion = idInscripcion;
       this.anioescolar = anioescolar;
       this.estudiante = estudiante;
       this.grado = grado;
       this.seccion = seccion;
       this.actividads = actividads;
       this.calificacions = calificacions;
    }
   
    public int getIdInscripcion() {
        return this.idInscripcion;
    }
    
    public void setIdInscripcion(int idInscripcion) {
        this.idInscripcion = idInscripcion;
    }
    public Anioescolar getAnioescolar() {
        return this.anioescolar;
    }
    
    public void setAnioescolar(Anioescolar anioescolar) {
        this.anioescolar = anioescolar;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public Set<Actividad> getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set<Actividad> actividads) {
        this.actividads = actividads;
    }
    public Set<Calificacion> getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set<Calificacion> calificacions) {
        this.calificacions = calificacions;
    }




}


