package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private int idNota;
     private Actividad actividad;
     private Estudiante estudiante;
     private BigDecimal nota;
     private Boolean borradoLogico;

    public Notas() {
    }

	
    public Notas(int idNota) {
        this.idNota = idNota;
    }
    public Notas(int idNota, Actividad actividad, Estudiante estudiante, BigDecimal nota, Boolean borradoLogico) {
       this.idNota = idNota;
       this.actividad = actividad;
       this.estudiante = estudiante;
       this.nota = nota;
       this.borradoLogico = borradoLogico;
    }
   
    public int getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(int idNota) {
        this.idNota = idNota;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }




}


