package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private Escuela escuela;
     private String cui;
     private String codigoPersonal;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private String nacionalidad;
     private String genero;
     private String rol;
     private Boolean borradoLogico;
     private Set<Cursodocente> cursodocentes = new HashSet<Cursodocente>(0);

    public Persona() {
    }

	
    public Persona(int idPersona, String cui, String codigoPersonal, String nombre, String apellido, Date fechaNacimiento, String nacionalidad, String genero, String rol) {
        this.idPersona = idPersona;
        this.cui = cui;
        this.codigoPersonal = codigoPersonal;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.nacionalidad = nacionalidad;
        this.genero = genero;
        this.rol = rol;
    }
    public Persona(int idPersona, Escuela escuela, String cui, String codigoPersonal, String nombre, String apellido, Date fechaNacimiento, String nacionalidad, String genero, String rol, Boolean borradoLogico, Set<Cursodocente> cursodocentes) {
       this.idPersona = idPersona;
       this.escuela = escuela;
       this.cui = cui;
       this.codigoPersonal = codigoPersonal;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.nacionalidad = nacionalidad;
       this.genero = genero;
       this.rol = rol;
       this.borradoLogico = borradoLogico;
       this.cursodocentes = cursodocentes;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getCui() {
        return this.cui;
    }
    
    public void setCui(String cui) {
        this.cui = cui;
    }
    public String getCodigoPersonal() {
        return this.codigoPersonal;
    }
    
    public void setCodigoPersonal(String codigoPersonal) {
        this.codigoPersonal = codigoPersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Cursodocente> getCursodocentes() {
        return this.cursodocentes;
    }
    
    public void setCursodocentes(Set<Cursodocente> cursodocentes) {
        this.cursodocentes = cursodocentes;
    }




}


