package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private int idSeccion;
     private Escuela escuela;
     private Grado grado;
     private char nombre;
     private Boolean borradoLogico;
     private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

    public Seccion() {
    }

	
    public Seccion(int idSeccion, char nombre) {
        this.idSeccion = idSeccion;
        this.nombre = nombre;
    }
    public Seccion(int idSeccion, Escuela escuela, Grado grado, char nombre, Boolean borradoLogico, Set<Inscripcion> inscripcions) {
       this.idSeccion = idSeccion;
       this.escuela = escuela;
       this.grado = grado;
       this.nombre = nombre;
       this.borradoLogico = borradoLogico;
       this.inscripcions = inscripcions;
    }
   
    public int getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(int idSeccion) {
        this.idSeccion = idSeccion;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public char getNombre() {
        return this.nombre;
    }
    
    public void setNombre(char nombre) {
        this.nombre = nombre;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Inscripcion> getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set<Inscripcion> inscripcions) {
        this.inscripcions = inscripcions;
    }




}


