package POJOs;
// Generated 22-sep-2024 18:38:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private int idSeccion;
     private Grado grado;
     private String nombreSeccion;
     private Boolean borradoLogico;
     private Set<AsignacionDocenteCurso> asignacionDocenteCursos = new HashSet<AsignacionDocenteCurso>(0);
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Seccion() {
    }

	
    public Seccion(int idSeccion, String nombreSeccion) {
        this.idSeccion = idSeccion;
        this.nombreSeccion = nombreSeccion;
    }
    public Seccion(int idSeccion, Grado grado, String nombreSeccion, Boolean borradoLogico, Set<AsignacionDocenteCurso> asignacionDocenteCursos, Set<Estudiante> estudiantes) {
       this.idSeccion = idSeccion;
       this.grado = grado;
       this.nombreSeccion = nombreSeccion;
       this.borradoLogico = borradoLogico;
       this.asignacionDocenteCursos = asignacionDocenteCursos;
       this.estudiantes = estudiantes;
    }
   
    public int getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(int idSeccion) {
        this.idSeccion = idSeccion;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getNombreSeccion() {
        return this.nombreSeccion;
    }
    
    public void setNombreSeccion(String nombreSeccion) {
        this.nombreSeccion = nombreSeccion;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<AsignacionDocenteCurso> getAsignacionDocenteCursos() {
        return this.asignacionDocenteCursos;
    }
    
    public void setAsignacionDocenteCursos(Set<AsignacionDocenteCurso> asignacionDocenteCursos) {
        this.asignacionDocenteCursos = asignacionDocenteCursos;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


