package POJOs;
// Generated 29-sep-2024 19:19:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private Integer idSeccion;
     private Grado grado;
     private String nombreSeccion;
     private Boolean borradoLogico;
     private Set asignacionDocenteCursos = new HashSet(0);
     private Set estudiantes = new HashSet(0);

    public Seccion() {
    }

	
    public Seccion(String nombreSeccion) {
        this.nombreSeccion = nombreSeccion;
    }
    public Seccion(Grado grado, String nombreSeccion, Boolean borradoLogico, Set asignacionDocenteCursos, Set estudiantes) {
       this.grado = grado;
       this.nombreSeccion = nombreSeccion;
       this.borradoLogico = borradoLogico;
       this.asignacionDocenteCursos = asignacionDocenteCursos;
       this.estudiantes = estudiantes;
    }
   
    public Integer getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(Integer idSeccion) {
        this.idSeccion = idSeccion;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getNombreSeccion() {
        return this.nombreSeccion;
    }
    
    public void setNombreSeccion(String nombreSeccion) {
        this.nombreSeccion = nombreSeccion;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set getAsignacionDocenteCursos() {
        return this.asignacionDocenteCursos;
    }
    
    public void setAsignacionDocenteCursos(Set asignacionDocenteCursos) {
        this.asignacionDocenteCursos = asignacionDocenteCursos;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


