package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unidad generated by hbm2java
 */
public class Unidad  implements java.io.Serializable {


     private int idUnidad;
     private Curso curso;
     private String nombre;
     private Boolean borradoLogico;
     private Set<Actividad> actividads = new HashSet<Actividad>(0);
     private Set<Calificacion> calificacions = new HashSet<Calificacion>(0);

    public Unidad() {
    }

	
    public Unidad(int idUnidad, String nombre) {
        this.idUnidad = idUnidad;
        this.nombre = nombre;
    }
    public Unidad(int idUnidad, Curso curso, String nombre, Boolean borradoLogico, Set<Actividad> actividads, Set<Calificacion> calificacions) {
       this.idUnidad = idUnidad;
       this.curso = curso;
       this.nombre = nombre;
       this.borradoLogico = borradoLogico;
       this.actividads = actividads;
       this.calificacions = calificacions;
    }
   
    public int getIdUnidad() {
        return this.idUnidad;
    }
    
    public void setIdUnidad(int idUnidad) {
        this.idUnidad = idUnidad;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }
    public Set<Actividad> getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set<Actividad> actividads) {
        this.actividads = actividads;
    }
    public Set<Calificacion> getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set<Calificacion> calificacions) {
        this.calificacions = calificacions;
    }




}


