package POJOs;
// Generated 16-sep-2024 21:46:47 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Escuela escuela;
     private Grado grado;
     private String nombreUsuario;
     private String contrasena;
     private String rol;
     private Boolean borradoLogico;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombreUsuario, String contrasena, String rol) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.rol = rol;
    }
    public Usuario(int idUsuario, Escuela escuela, Grado grado, String nombreUsuario, String contrasena, String rol, Boolean borradoLogico) {
       this.idUsuario = idUsuario;
       this.escuela = escuela;
       this.grado = grado;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.rol = rol;
       this.borradoLogico = borradoLogico;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Boolean getBorradoLogico() {
        return this.borradoLogico;
    }
    
    public void setBorradoLogico(Boolean borradoLogico) {
        this.borradoLogico = borradoLogico;
    }




}


